#! /bin/sh

set -e

. "${GODI_PREFIX}/lib/godi/install_helper"

godi_env_add(){
    local ENVNAME ENVVALUE ENVDAT tmpfln
    if [ "a${2}" = "aPOST-INSTALL" ] ; then
        ENVDAT="${GODI_PREFIX}/etc/env_add" 
        if [ -f "${ENVDAT}" ]; then
            ENVNAME=$3
            ENVVALUE=$4
 
            tmpfln="$(mktemp)"
            trap "rm -f \"${tmpfln}\"" EXIT
            grep -v "$ENVNAME" "$ENVDAT" > "$tmpfln"
            echo "" >> "$tmpfln"
            echo "${ENVNAME}|${ENVVALUE}" >> "$tmpfln"
            grep -v '^$' "$tmpfln" > "$ENVDAT"
        fi
    fi
}

godi_env_add "$1" "$2" "FRAMAC_SHARE" "${GODI_PREFIX_WIN}/share/frama-c"
godi_env_add "$1" "$2" "FRAMAC_LIB" "${GODI_PREFIX_WIN}/lib/frama-c"

winadd  "$1" "$2" 1  \
        --add-to-startmenu \
        bin/frama-c-gui.exe \
        "Frama-C" \
        "" \
        "" \
        "" \
        ""

exit 0
