#! /bin/sh

set -e

. "${GODI_PREFIX}/lib/godi/install_helper"

if [ "a${2}" != "aDEINSTALL" ]; then
    exit 0
fi

restore_backup "${GODI_PREFIX}/lib/ocaml/pkg-lib/lablgtk2/build.ml"
# restore_backup "${GODI_PREFIX}/bin/lablgtk2"

exit 0
