#! /bin/sh

set -e

. "${GODI_PREFIX}/lib/godi/install_helper"

windel  "$1" "$2" 1 \
    --remove-from-startmenu \
    opt/Console2/Console.exe \
    "Console2" \
    "" \
    "--no-cygwin" \
    "" \
    ""

windel  "$1" "$2" 1 \
    --remove-from-startmenu \
    opt/Console2/Console.exe \
    "Console2 (with cygwin)" \
    "" \
    "" \
    "" \
    ""

exit 0
