#! /bin/sh

set -e

. "${GODI_PREFIX}/lib/godi/install_helper"

windel  "$1" "$2" 1 \
    --remove-from-startmenu \
    gui/bin/ocamleditor \
    "Ocamleditor" \
    "" \
    "--with-mintty --with-bash" \
    "" \
    ""
#--with-mintty --with-bash
exit 0
