#! /bin/sh

set -e

. "${GODI_PREFIX}/lib/godi/install_helper"

winadd \
    "$1" "$2" 1 \
    --add-to-startmenu \
    gui/bin/ocamltop-gtk.exe \
    "Ocamltop GTK" \
    "" \
    "--with-mintty" \
    "" \
    ""

exit 0
