.include "../../mk/bsd.prefs.mk"

VERSION=	0.4.1
PKG=		godi-integration1d
PKGNAME=	${PKG}-${VERSION}
PKGREVISION=	0
DISTNAME=	integration1d-0.4.1
DISTFILES=	integration1d-0.4.1.tar.gz
CATEGORIES=	godi
MASTER_SITES=	https://forge.ocamlcore.org/frs/download.php/1149/
HOMEPAGE=	http://forge.ocamlcore.org/projects/integration1d/
COMMENT=	Integration of functions of one variable

DEPENDS+=	godi-ocaml-*:../../godi/godi-ocaml
BUILD_DEPENDS+= godi-findlib-*:../../godi/godi-findlib


WINOASIS=		yes



.include "../../mk/bsd.pkg.mk"
