#!/bin/sh -e

. ./tcltkversion.mk

cur_dir=`dirname "$0"`
cur_dir=`cd "${cur_dir}"; pwd`
confinc="${cur_dir}/configure-tk.inc"

SUBDIR=`uname -s`
case "$SUBDIR" in
    CYGWIN*)
        SUBDIR=win
        ;;
    MINGW*)
        SUBDIR=win
        ;;
    Darwi*)
        SUBDIR=macosx
        #not tested at all ...
        ;;
    *)
        SUBDIR=unix
        ;;
esac

cd "tk${TCLTKVERSION}/${SUBDIR}"
. "$confinc"
cd "$cur_dir"
echo "ok" >configure-tk.ok
exit 0
