#! /bin/sh

set -e

. "${GODI_PREFIX}/lib/godi/install_helper"

winadd  "$1" "$2" 1 \
    --add-to-startmenu \
    bin/ocamlbrowser.exe \
    "Ocamlbrowser" \
    "" \
    "" \
    "" \
    ""

exit 0
