#!/bin/sh
unset AR
unset AS
unset CC
unset CPP
unset CPPFILT
unset CXX
unset DLLTOOL
unset DLLWRAP
unset GCOV
unset LD
unset NM
unset OBJCOPY
unset OBJDUMP
unset RANLIB
unset RC
unset READELF
unset SIZE
unset STRINGS
unset STRIP
unset WINDMC
unset WINDRES

cd "$(dirname "$0")"
exec ./Configure "$@"
