.include "../../mk/bsd.prefs.mk"

VERSION=	0.4
PKG=		godi-pa_where
PKGNAME=	${PKG}-${VERSION}
PKGREVISION=	1
DISTNAME=	cakeplus-pa_where-ddcf36dd86a4
DISTFILES=	pa_where-0.4.tar.gz
CATEGORIES=	godi
MASTER_SITES=	${MASTER_SITE_BACKUP}
HOMEPAGE=	https://bitbucket.org/cakeplus/pa_where/
COMMENT=	Backward declaration syntax

DEPENDS+=	godi-ocaml-*:../../godi/godi-ocaml
DEPENDS+= 	godi-camlp4>=0:../../godi/godi-camlp4
BUILD_DEPENDS+= godi-findlib-*:../../godi/godi-findlib


WINOASIS=		yes



.include "../../mk/bsd.pkg.mk"
