#!/bin/bash


to_add="$(dirname "$0")"
to_add="${to_add}/ocamlscript_real.exe"

finished=0

while [ $# -gt 0 ]; do
    if [ $finished -ne 0 ]; then
        to_add="$(printf "%s %q" "$to_add" "$1")"
        shift
    else
        case "$var" in
            '-')
                to_add="$(printf "%s %q" "$to_add" "$1")"
                finished=1
                ;;
            '-help'|'--help'|'-c'|'-f'|'-debug'|'-version')
                to_add="$(printf "%s %q" "$to_add" "$1")"
                ;;
            '-o'|'-vm')
                prog="$(cygpath -m "$2")"
                to_add="$(printf "%s %q %q" "$to_add" "$1" "$2")"
                shift
                ;;
            '-e'|'--')
                prog="$(cygpath -m "$2")"
                to_add="$(printf "%s %q %q" "$to_add" "$1" "$2")"
                finished=1
                shift
                ;;
            *)
                prog="$(cygpath -m "$1")"
                to_add="$(printf "%s %q" "$to_add" "$prog")"
                finished=1
                ;;
        esac
        shift
    fi
done

# make sure ocamlscript finds a suitable tmp location
TMP="$(cygpath -m "/tmp")"
TEMP=$TMP
export TMP TEMP
eval "$to_add"
