#! /bin/sh

set -e

. "${GODI_PREFIX}/lib/godi/install_helper"

winadd \
    "$1" "$2" 1 \
    --add-to-startmenu \
    gui/bin/ocamltopwin.exe \
    "Ocamltop Win" \
    "" \
    "" \
    "" \
    ""



exit 0
