#! /bin/sh

set -e

. "${GODI_PREFIX}/lib/godi/install_helper"

windel  "$1" "$2" 1 \
    --remove-from-startmenu \
        gui/bin/graph-editor.exe \
        "Ocamlgraph Editor" \
        "" \
        "" \
        "" \
        ""

windel  "$1" "$2" 1 \
    --remove-from-startmenu \
        gui/bin/graph-viewer.exe \
        "Ocamlgraph Viewer" \
        "" \
        "" \
        "" \
        ""

exit 0
