#! /bin/sh

set -e

. "${GODI_PREFIX}/lib/godi/install_helper"

if [ "a${2}" != "aDEINSTALL" ]; then
    exit 0
fi

for f in \
    lib/ocaml/pkg-lib/META.ocp-index \
    lib/ocaml/pkg-lib/META.ocp-index-lib
do
    xfile="${GODI_PREFIX}/${f}"
    if [ -f "${xfile}" ]; then
        restore_backup "${xfile}"
    fi
done
exit 0
