.include "../../mk/bsd.prefs.mk"

VERSION=	1.0.1
PKG=		godi-mparser
PKGNAME=	${PKG}-${VERSION}
PKGREVISION=	0
DISTNAME=	cakeplus-mparser-c9ea603927b4
DISTFILES=	mparser-1.0.1.tar.gz
CATEGORIES=	godi
MASTER_SITES=	${MASTER_SITE_BACKUP}
HOMEPAGE=	https://bitbucket.org/cakeplus/mparser/
COMMENT=	monadic parser combinator library

DEPENDS+=	godi-pcre-*:../../godi/godi-pcre
DEPENDS+=	godi-ocaml-*:../../godi/godi-ocaml
BUILD_DEPENDS+= godi-findlib-*:../../godi/godi-findlib


WINOASIS=		yes



.include "../../mk/bsd.pkg.mk"
