.include "../../mk/bsd.prefs.mk"

VERSION=	0.5.1
PKG=		godi-optimization1d
PKGNAME=	${PKG}-${VERSION}
PKGREVISION=	1
DISTNAME=	optimization1d-0.5.1
DISTFILES=	optimization1d-0.5.1.tar.gz
CATEGORIES=	godi
MASTER_SITES=	http://forge.ocamlcore.org/frs/download.php/1124/
HOMEPAGE=	http://forge.ocamlcore.org/projects/optimization1d/
COMMENT=	Find extrema of 1D functions

DEPENDS+=	godi-ocaml-*:../../godi/godi-ocaml
BUILD_DEPENDS+= godi-findlib-*:../../godi/godi-findlib


WINOASIS=		yes



.include "../../mk/bsd.pkg.mk"
