#! /bin/sh

set -e

. "${GODI_PREFIX}/lib/godi/install_helper"

windel  "$1" "$2" 1 \
    --remove-from-startmenu \
    opt/eclipse/eclipse.exe \
    "Eclipse" \
    "" \
    "" \
    "" \
    ""

exit 0
