.include "../../mk/bsd.prefs.mk"

VERSION=	0.3
PKG=		godi-root1d
PKGNAME=	${PKG}-${VERSION}
PKGREVISION=	0
DISTNAME=	root1d-0.3
DISTFILES=	root1d-0.3.tar.gz
CATEGORIES=	godi
MASTER_SITES=	http://forge.ocamlcore.org/frs/download.php/1125/
HOMEPAGE=	http://forge.ocamlcore.org/projects/root1d/
COMMENT=	Find roots of 1D functions

DEPENDS+=	godi-ocaml-*:../../godi/godi-ocaml
BUILD_DEPENDS+= godi-findlib-*:../../godi/godi-findlib


WINOASIS=		yes



.include "../../mk/bsd.pkg.mk"
