.include "../../mk/bsd.prefs.mk"

VERSION=	0.2
PKG=		godi-textwrap
PKGNAME=	${PKG}-${VERSION}
PKGREVISION=	0
DISTNAME=	ocaml-textwrap-0.2
DISTFILES=	textwrap-0.2.tar.xz
CATEGORIES=	godi
MASTER_SITES=	${MASTER_SITE_BACKUP}
HOMEPAGE=	https://github.com/superbobry/ocaml-textwrap
COMMENT=	Text wrapping and filling library

DEPENDS+=	godi-ocaml-*:../../godi/godi-ocaml
BUILD_DEPENDS+= godi-findlib-*:../../godi/godi-findlib


WINOASIS=		yes



.include "../../mk/bsd.pkg.mk"
