.include "../../mk/bsd.prefs.mk"

VERSION=	1.2.2
PKG=		godi-re
PKGNAME=	${PKG}-${VERSION}
PKGREVISION=	0
DISTNAME=	ocaml-re-ocaml-re-1.2.2
DISTFILES=	ocaml-re-1.2.2.tar.gz
CATEGORIES=	godi
MASTER_SITES=	https://github.com/ocaml/ocaml-re/archive/
HOMEPAGE=	https://github.com/ocaml/ocaml-re
COMMENT=	Regular expressions

DEPENDS+=	godi-ocaml-*:../../godi/godi-ocaml
BUILD_DEPENDS+= godi-findlib-*:../../godi/godi-findlib


WINOASIS=		yes



.include "../../mk/bsd.pkg.mk"
