#! /bin/sh

set -e

. "${GODI_PREFIX}/lib/godi/install_helper"

windel  "$1" "$2" 1 \
    --remove-from-startmenu \
    opt/Console2/Console.exe \
    "Utop" \
    "-r \"/c utop.exe\"" \
    "" \
    "" \
    ""

exit 0
