#! /bin/sh

set -e

. "${GODI_PREFIX}/lib/godi/install_helper"

winadd  "$1" "$2" 1 \
    --add-to-startmenu \
    opt/Console2/Console.exe \
    "Utop" \
    "-r \"/c utop.exe\"" \
    "" \
    "" \
    ""

exit 0
